# SQL Server (2012 or higher required)
#

default: &default
  adapter: sqlserver
  encoding: utf8

development:
  <<: *default
  host: localhost
  database: <%= "sam50_#{ENV['MODE']}_development" %>
  username: dev
  password: password

test:
  <<: *default
  host: localhost
  database: <%= "sam50_#{ENV['MODE']}_test" %>
  username: test
  password: password

production:
  <<: *default
  host: localhost
  database: sam50_production
  username:
  password:
